# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Ahmed Chaouachi
title: Senior Lead AI scientist
email: ahmad.chaouachi@gmail.com
website: chaouachi.github.io

# Social links
twitter_username: chaouachi
github_username:  chaouachi
# dribbble_username: jekyll
facebook_username: chaouaca
# flickr_username: jekyll
instagram_username: ahmedsoulaimaaziz
linkedin_username: ahmed-chaouachi-37122830
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/myPic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ahmed and I'm a senior data scientist leading AI projects. I have done over 10 years of applied research science in  machine learning and optimization. I served worldwide large companies in Telecommunication, Retail,  Energy and Airline industries. I~have bias for action, I am client obsessed and I have relentlessly high standards. I have recent experience on managing data scientists and leading AI projects from exploratory phases to the scalable integration.

  I am most skilled in: <mark>Optimization</mark> and <mark>machine learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: chaouachi

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
